### ISSUE TITLE
Change Timestamp column in job_instance_status for mysql

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#11]
During some "crazy" default beaviour with timestamps in mysql, at least the timestamps for job_start and job_stop should be decared with default "null" as follows:

JOB_STARTED_AT TIMESTAMP(3) NULL default NULL,
JOB_ENDED_AT TIMESTAMP(3) NULL default NULL,

Else the mysql assigns 0 as default, wich will result in exceptions, when reading the timestamps with talend.

**Comment by jlolling** [comment]
Documentation fixed
