### ISSUE TITLE
Refactor Counter Configuration Elements

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#15]
I know, the following is hard to construct backwards compatible but I think it will make tJobinstanceStop less complex and provide potential extensability.
Instead of providing dedicated table elements in the component to add Input/Ouput Counters, it can be more efficent by just having one table element to configure all counters. Mapping the single entries to the summarizing category would be done by an additional first column with a dropdown box to select the category (input, output,reject...).

This single table can use more space an would show for normal jobs  configured elements without any scrolling. Since, categorization is no longer a "hard coded"  feature, an extention to more categories, can be done easy.

For Migration from the old Version, a job, needs to migrate all item files. This might be the hard part to provide on rollout. A soft method would be the possilitiy to switch the behaviour and concept with a checkbox, and let the developers decide, wich way they will use it. Both methods would be compatible with the new datamodel of issue #7

**Comment by jlolling** [comment]
I will restore the fields job_display_name and process_instance_name.
