### ISSUE TITLE
Get Counts from monitored flows

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#16]
As an alternative to retrieve counters from the global map it would be nice to get the count information from "monitored" flows. Working with this feature would be like follows:

1. Mark flows to count as "monitored"
2. in tJobinstanceEnd: enter name* of the flow and declare a countergroup and counter name
\* or select name from a dropdown, if possible

tJobInstanceEnd should act as follows:

- in generation/compile phase 
  - throw an error  if the flow does not exist or is not marked 
  - throw a warning if a monitored flow is not entered as counter
- capture and summarize the count data (flows in iterations will throw a value for each iteration)
- if no data was captured for the counter in the whole jobrun, register a zero for the counter

**Comment by jlolling** [comment]
I have checked that. Currently I do not see a way to catch these counters.
