### ISSUE TITLE
tJobInstanceEnd does not always commit 

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#18]
tJobinstanceEnd does not commit its update under following circumstances:
Connection in the main job is set with autocommit "off" on "on" (doesent matter in this case).
Job calls a subjob wich reuses uses the connection but does not contain tJobinstances. (It's a module for some extended management of  job metadata). In the subjob also setting autocommit to "off" in the connection component and using an explicit  commit.

In this case, only the initial start data is written to job_instance_status. JobInstanceEnd data is not commited.

When I deactivate the subjob, all works fine in the main job.
When I set connection to autcommit in the subjob it also works fine.

**Comment by jlolling** [comment]
I will check that, I am currently working on other issues - good timing!

**Comment by jlolling** [comment]
Release 6.2 will solve this possible problem by always checking the auto commit state just before we use the connection.
