### ISSUE TITLE
Create job_instance_id not by sequence 

### ISSUE THREAD

**Issue by jlolling** [jlolling/talendcomp_tJobInstance#2]
This number should by made of job name and timestamp, so these data can be migrated between different stages.

**Comment by mattywausb** [comment]
The best method to generate the unique number should be discussed. The procedure must consider the following usecases:
starting the job for multiple input containers in parallel
starting multiple instances distributed over multiple hosts

**Comment by jlolling** [comment]
I am working on it. I have currently 2 different approaches in work.

**Comment by jlolling** [comment]
This is done with a appropriated option in the advanced settings.
