### ISSUE TITLE
Need to add column COUNTER_TYPE to table JOB_INSTANCE_COUNTERS 

### ISSUE THREAD

**Issue by lucvanlinden** [jlolling/talendcomp_tJobInstance#24]
In the DDL in the PDF document you need to add column COUNTER_TYPE to table JOB_INSTANCE_COUNTERS.

When the check box "save named counters" is thicked for teh Job_instance_end, it will raise an error on the underlying INSERT statement:

insert into dwh.JOB_INSTANCE_COUNTERS (JOB_INSTANCE_ID,COUNTER_NAME,COUNTER_TYPE,COUNTER_VALUE) values (15,'ReadMetadataEntries','output',5) was aborted: ERROR: column "counter_type" of relation "job_instance_counters" does not exist.

That column is currently missing from the DDL in the documentation.

Work-arround:  alter table dwh.job_instance_counters add column counter_type varchar(25);

**Comment by jlolling** [comment]
Is done.
