### ISSUE TITLE
SLF4J:  Faild to load class in TOS 6.x

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#27]
Release 8.2: 
When tJobinstanceStart is used in TOS 6.3 or 6.5 I get a warning on stderr (or at least in red) at start:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Further processing is normal.

**Comment by jlolling** [comment]
This error message can be ignored. It means the used logging framework in the component is not ready to run. I have recently decided to replace the SL4J framework with Log4J v2 which is used as default in Talend jobs.
