### ISSUE TITLE
Inconsistency in memory logging feature

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#28]
Release 8.2, Talend TOS 6.x:
When activating "Memory Usage Monitoring" there only the output of the time of the peak usage but not the usage itself. 
Usage must be logged by own code now. Former versions printed all values to console.

This is what I get now:

|134                 |Van Buren|Missouri   |
|134                 |Kennedy  |Alaska     |
|134                 |Carter   |Missouri   |
'--------------------+---------+-----------'

Maximum of memory usage measured at: 2021-10-12 16:05:44
2021-10-12 16:05:44|eGvJPX|eGvJPX|eGvJPX|41596|ETLFRAMEWORK|template_demo_no_context_load__pg|_AEkDECtsEeyJ0sp_R7CZAQ|1.0|dev1||end|success|396

Removal of the consol output and providing the values only as return variables, has huge impact in case of upgrade in older projects, since we would need to add extra components to every job, to print the values.
Please integrate the console print again.

**Comment by jlolling** [comment]
Hi Matthias, I agree with you. But by the way, feel free to implement this by your self and create a push request. I will accept this of course.
I will restore the console output next week.
