### ISSUE TITLE
Return Errorcode 0 after an exception

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#6]
It is not possible overwrite the returncode to 0 when catching an exception inside of the job.
This would be nice to catch irrelevant errors and declare the run as valid. (e.g. an error in some post processing, after all data was transformed and loaded)

**Comment by jlolling** [comment]
The return code should be exactly the same as the exit code of the job. This was the design goal.
If an error should not be a reason to let the job fail, we should organize it in the job itself.
