### ISSUE TITLE
Extend Job_instance_counters table by "CouterGroup" column

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#7]
It would be helpful, to have a marking in the job_instance_counter table, wich represents the "general counter group" in the tJobInstanceEnd.  This can be a 1 char colums holding one of the following markers:
I = input
O= output
U = update
D = delete
R = reject
G = ignore (see "Ignore" counter issue)

**Comment by cyroxx** [comment]
By "Ignore counter issue" you probably mean #5?

**Comment by jlolling** [comment]
Yes, this feature can easily be done.

**Comment by mattywausb** [comment]
Feature is implemented as COUNTER_TYPE column. Documentation is pending
