### ISSUE TITLE
Extend job_instance_status by job revision

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJobInstance#8]
Beside the general name of a running job, it would be great to know its exact revision/build id/version/save date.

I'm suggesting the following solution:
Add a column "job_revision_information" to the job_instance_status table.
Add a new Field "Revision information" to tJobInstance start, where you can declare an expression, that shall be put into the new column. Default is "$Id$". Add a checkbox, "use timestampt from jobinfo.properties". Default is "yes".

In Default mode, the component searches for the jobInfo.properties file of the job and uses the date information in that file. The file is created by the build process of talend and does not exist when running the job in the studio.

Unchecking the "use timestamp from jobInfo.propteries" gives full control to the developer how to insert version information. Here are two possible solutions:
He can put here some replacement string, that will be detected and rewritten by the version control system . (e.g. commit to svn -> build by commandline).
He can use a context variable and rewrite the information in the context properties files of the job during the building or deployment process. (Probably better, when not using the talend toolchain for build and deployment. So build might happen before Version Control system is adding its information)

**Comment by jlolling** [comment]
The job revision is part of the field JOB_INFO in the JOB_INSTANCE_STATUS table. Is this not good enough?

**Comment by jlolling** [comment]
Not possible yet because the job does not know anything about its revision.
